### ISSUE TITLE
public key + signatures

### ISSUE THREAD

**Issue by jonmorehouse** [jonmorehouse/safe#3]
Right now, `safe` relies on a user's local `gpg` for public keys. It does not verify public key signatures at encryption time.

As a first pass, I propose the following changes:

**1.** the `recipients` array in `safe.yml` is expanded to be a `dict` of the following format:

```yaml
recipients:
   - email: morehousej09@gmail.com
     nickname: jon
     pub_key: '<ASC BLOCK>'
	 signature: '1234456678'
``` 

Since not all keys specify a `nickname` or `email` we provide these configurable blocks in the `safe` config. This allows us to simplify some of the logic.

Encryption will verify the key signatures

**2.** Expose a `safe identify` or `safe.Username()` method to the cli / package. This will allow automated workflows that rely on acls (such as a build / slackbot) to leverage the identity associated with the key.
